_BASE_: "Base-WordLenSpotter.yaml"
MODEL:
  WEIGHTS: "./output/MixTRAIN150K/model_final.pth" 
  SWINTS:
    NUM_PROPOSALS: 600
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("dstd1500_train",)
  TEST:  ("dstd1500_test",)
SOLVER:
  STEPS: (6000,)  
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: "./output/FINETUNE20K/"