_BASE_: "Base-WordLenSpotter.yaml"
MODEL:
  WEIGHTS: "./weights/swin_imagenet_pretrain.pth"
  SWINTS:
    NUM_PROPOSALS: 600
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("totaltext_train","icdar2015_train","icdar_2013_train","icdar_2017_validation_mlt","icdar_2017_mlt","icdar_curvesynthtext_train1","icdar_curvesynthtext_train2",)
  TEST:  ("dstd1500_test",)

SOLVER:
  STEPS: (360000,420000)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 10000

INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: "./output/PreTRAIN450K/"